
PATTERN_FOLDER = "patterns/"

LOG_TABS = 0

Z1_CSS = "z1.css"
Z1_TEMP_SVG = "z1.temp.svg"

STANDARD_ATOM_RADIUS = 20

STANDARD_DISTANCE_BETWEEN_LIGATIONS = 20

STANDARD_WAVES = {
    { 0 },
    {STANDARD_DISTANCE_BETWEEN_LIGATIONS / 2, -STANDARD_DISTANCE_BETWEEN_LIGATIONS / 2},
    {STANDARD_DISTANCE_BETWEEN_LIGATIONS, 0, -STANDARD_DISTANCE_BETWEEN_LIGATIONS}
}