
PATTERN_FOLDER = "patterns/"

LOG_TABS = 0

Z1_CSS = "zuna/z1.css"
Z1_TEMP_SVG = "zuna/z1.temp.svg"

STANDARD_ATOM_RADIUS = 8
STANDARD_DISTANCE_BETWEEN_LIGATIONS = 20
STANDARD_LIGATION_SIZE = 30

STANDARD_WAVES = {
    { 0 },
    {STANDARD_DISTANCE_BETWEEN_LIGATIONS / 2, -STANDARD_DISTANCE_BETWEEN_LIGATIONS / 2},
    {STANDARD_DISTANCE_BETWEEN_LIGATIONS, 0, -STANDARD_DISTANCE_BETWEEN_LIGATIONS}
}

SVG_BORDER = 10